"use server"

import { revalidatePath } from "next/cache"
import { createClient } from "@/lib/supabase/server"
import { recordStockMovement } from "@/lib/db/stock-movements"
import { getSessionOrRedirect } from "@/lib/auth"
import type {
  CreateSaleReturnInput,
  CreatePurchaseReturnInput,
  CreateRefundInput,
  Return,
  ReturnWithDetails,
  Refund,
} from "@/lib/types/return"

export async function createSaleReturn(payload: CreateSaleReturnInput) {
  const currentUser = await getSessionOrRedirect()
  const supabase = createClient()

  if (!payload.sales_invoice_id || !payload.items?.length) {
    return { error: "Sales invoice and at least one line item are required", data: null }
  }

  // Verify the sales invoice exists and belongs to user
  const { data: salesInvoice, error: invoiceError } = await supabase
    .from("sales_invoices")
    .select("id, party_id, total")
    .eq("id", payload.sales_invoice_id)
    .eq("user_id", currentUser.id)
    .single()

  if (invoiceError || !salesInvoice) {
    return { error: "Sales invoice not found", data: null }
  }

  const taxRate = payload.taxRate ?? 18
  const subtotal = payload.items.reduce((sum, item) => sum + item.quantity * item.unitPrice, 0)
  const tax = subtotal * (taxRate / 100)
  const total = subtotal + tax

  // Verify party belongs to user
  const { data: party } = await supabase
    .from("parties")
    .select("id")
    .eq("id", payload.party_id)
    .eq("user_id", currentUser.id)
    .single()

  if (!party) {
    return { error: "Party not found", data: null }
  }

  // Verify all items belong to user
  const itemIds = payload.items.map((item) => item.itemId)
  const { data: items } = await supabase
    .from("inventory_items")
    .select("id")
    .in("id", itemIds)
    .eq("user_id", currentUser.id)

  if (!items || items.length !== itemIds.length) {
    return { error: "One or more items not found", data: null }
  }

  // Create return (return_number will be auto-generated by trigger)
  const { data: returnData, error: returnError } = await supabase
    .from("returns")
    .insert({
      type: "sale",
      sales_invoice_id: payload.sales_invoice_id,
      purchase_invoice_id: null,
      party_id: payload.party_id,
      subtotal,
      tax,
      total,
      status: "Completed", // Auto-complete returns
      user_id: currentUser.id,
    })
    .select("id, return_number")
    .single()

  if (returnError || !returnData) {
    return { error: returnError?.message ?? "Unable to create return", data: null }
  }

  // Create return lines
  const lineItems = payload.items.map((item) => ({
    return_id: returnData.id,
    item_id: item.itemId,
    quantity: item.quantity,
    unit_price: item.unitPrice,
    line_total: item.quantity * item.unitPrice,
    sales_invoice_line_id: item.salesInvoiceLineId || null,
    purchase_invoice_line_id: null,
  }))

  const { error: lineError } = await supabase.from("return_lines").insert(lineItems)
  if (lineError) {
    return { error: lineError.message, data: null }
  }

  // Reverse stock (add stock back) - Sale return means stock comes back IN
  try {
    await Promise.all(
      payload.items.map(async (item) => {
        const { error: incrementError } = await supabase.rpc("increment_inventory_stock", { item_id: item.itemId, quantity: item.quantity })
        if (incrementError) {
          throw new Error(`Failed to restore stock for item ${item.itemId}: ${incrementError.message}`)
        }

        await recordStockMovement({
          itemId: item.itemId,
          movementType: "IN",
          quantity: item.quantity,
          referenceType: "SaleReturn",
          referenceId: returnData.id,
          notes: `Sale return ${returnData.return_number}`,
          userId: currentUser.id,
        })
      }),
    )
  } catch (error) {
    return { error: error instanceof Error ? error.message : "Failed to process inventory", data: null }
  }

  // Process refunds if provided
  if (payload.refunds && payload.refunds.length > 0) {
    const refundRows = payload.refunds
      .filter((r) => r.amount > 0)
      .map((r) => ({
        return_id: returnData.id,
        amount: r.amount,
        method: r.method,
        reference: r.reference || null,
        user_id: currentUser.id, // Add user_id for multi-tenant isolation
      }))

    if (refundRows.length > 0) {
      const { error: refundError } = await supabase.from("refunds").insert(refundRows)
      if (refundError) {
        // Don't fail the return if refund fails, but log it
        console.error("Error creating refunds:", refundError)
      }
    }
  }

  revalidatePath("/returns")
  revalidatePath("/returns/sales")
  revalidatePath("/returns/reports")
  revalidatePath("/accounts-management")
  revalidatePath("/dashboard")
  return { error: null, data: { returnId: returnData.id, returnNumber: returnData.return_number } }
}

export async function createPurchaseReturn(payload: CreatePurchaseReturnInput) {
  const currentUser = await getSessionOrRedirect()
  const supabase = createClient()

  if (!payload.purchase_invoice_id || !payload.items?.length) {
    return { error: "Purchase invoice and at least one line item are required", data: null }
  }

  // Verify the purchase invoice exists and belongs to user
  const { data: purchaseInvoice, error: invoiceError } = await supabase
    .from("purchase_invoices")
    .select("id, party_id, total")
    .eq("id", payload.purchase_invoice_id)
    .eq("user_id", currentUser.id)
    .single()

  if (invoiceError || !purchaseInvoice) {
    return { error: "Purchase invoice not found", data: null }
  }

  // Verify party belongs to user
  const { data: party } = await supabase
    .from("parties")
    .select("id")
    .eq("id", payload.party_id)
    .eq("user_id", currentUser.id)
    .single()

  if (!party) {
    return { error: "Party not found", data: null }
  }

  // Verify all items belong to user
  const itemIds = payload.items.map((item) => item.itemId)
  const { data: items } = await supabase
    .from("inventory_items")
    .select("id")
    .in("id", itemIds)
    .eq("user_id", currentUser.id)

  if (!items || items.length !== itemIds.length) {
    return { error: "One or more items not found", data: null }
  }

  const taxRate = payload.taxRate ?? 18
  const subtotal = payload.items.reduce((sum, item) => sum + item.quantity * item.unitPrice, 0)
  const tax = subtotal * (taxRate / 100)
  const total = subtotal + tax

  // Create return
  const { data: returnData, error: returnError } = await supabase
    .from("returns")
    .insert({
      type: "purchase",
      sales_invoice_id: null,
      purchase_invoice_id: payload.purchase_invoice_id,
      party_id: payload.party_id,
      subtotal,
      tax,
      total,
      status: "Completed",
      user_id: currentUser.id,
    })
    .select("id, return_number")
    .single()

  if (returnError || !returnData) {
    return { error: returnError?.message ?? "Unable to create return", data: null }
  }

  // Create return lines
  const lineItems = payload.items.map((item) => ({
    return_id: returnData.id,
    item_id: item.itemId,
    quantity: item.quantity,
    unit_price: item.unitPrice,
    line_total: item.quantity * item.unitPrice,
    sales_invoice_line_id: null,
    purchase_invoice_line_id: item.purchaseInvoiceLineId || null,
  }))

  const { error: lineError } = await supabase.from("return_lines").insert(lineItems)
  if (lineError) {
    return { error: lineError.message, data: null }
  }

  // Reverse stock (remove stock) - Purchase return means stock goes OUT
  try {
    await Promise.all(
      payload.items.map(async (item) => {
        const { error: decrementError } = await supabase.rpc("decrement_inventory_stock", { item_id: item.itemId, quantity: item.quantity })
        if (decrementError) {
          throw new Error(`Failed to decrement stock for item ${item.itemId}: ${decrementError.message}`)
        }

        await recordStockMovement({
          itemId: item.itemId,
          movementType: "OUT",
          quantity: item.quantity,
          referenceType: "PurchaseReturn",
          referenceId: returnData.id,
          notes: `Purchase return ${returnData.return_number}`,
          userId: currentUser.id,
        })
      }),
    )
  } catch (error) {
    return { error: error instanceof Error ? error.message : "Failed to process inventory", data: null }
  }

  // Process refunds if provided
  if (payload.refunds && payload.refunds.length > 0) {
    const refundRows = payload.refunds
      .filter((r) => r.amount > 0)
      .map((r) => ({
        return_id: returnData.id,
        amount: r.amount,
        method: r.method,
        reference: r.reference || null,
      }))

    if (refundRows.length > 0) {
      const refundRowsWithUserId = refundRows.map((r) => ({ ...r, user_id: currentUser.id }))
      const { error: refundError } = await supabase.from("refunds").insert(refundRowsWithUserId)
      if (refundError) {
        console.error("Error creating refunds:", refundError)
      }
    }
  }

  revalidatePath("/returns")
  revalidatePath("/returns/purchases")
  revalidatePath("/returns/reports")
  revalidatePath("/accounts-management")
  revalidatePath("/dashboard")
  return { error: null, data: { returnId: returnData.id, returnNumber: returnData.return_number } }
}

export async function getReturns(
  type?: "sale" | "purchase",
  dateFrom?: string,
  dateTo?: string,
  partyId?: string,
) {
  const currentUser = await getSessionOrRedirect()
  const supabase = createClient()

  let query = supabase
    .from("returns")
    .select(
      `
      id,
      return_number,
      type,
      sales_invoice_id,
      purchase_invoice_id,
      party_id,
      subtotal,
      tax,
      total,
      status,
      created_at,
      updated_at,
      parties:party_id (
        id,
        name,
        phone
      )
    `,
    )
    .eq("user_id", currentUser.id)
    .order("created_at", { ascending: false })

  if (type) {
    query = query.eq("type", type)
  }

  if (dateFrom) {
    const from = dateFrom.includes("T") ? dateFrom : `${dateFrom}T00:00:00.000Z`
    query = query.gte("created_at", from)
  }

  if (dateTo) {
    const to = dateTo.includes("T") ? dateTo : `${dateTo}T23:59:59.999Z`
    query = query.lte("created_at", to)
  }

  if (partyId) {
    query = query.eq("party_id", partyId)
  }

  const { data, error } = await query

  if (error) {
    return []
  }

  return (data ?? []).map((row: any) => {
    const partyData = row.parties ? (Array.isArray(row.parties) ? row.parties[0] : row.parties) : null
    return {
      id: row.id,
      return_number: row.return_number,
      type: row.type,
      sales_invoice_id: row.sales_invoice_id,
      purchase_invoice_id: row.purchase_invoice_id,
      party_id: row.party_id,
      subtotal: Number(row.subtotal ?? 0),
      tax: Number(row.tax ?? 0),
      total: Number(row.total ?? 0),
      status: row.status ?? "Draft",
      created_at: row.created_at,
      updated_at: row.updated_at,
      party: partyData
        ? {
            id: partyData.id,
            name: partyData.name,
            phone: partyData.phone,
          }
        : undefined,
    } as Return
  })
}

export async function getReturnById(returnId: string): Promise<ReturnWithDetails | null> {
  const currentUser = await getSessionOrRedirect()
  const supabase = createClient()

  const { data: returnData, error: returnError } = await supabase
    .from("returns")
    .select(
      `
      id,
      return_number,
      type,
      sales_invoice_id,
      purchase_invoice_id,
      party_id,
      subtotal,
      tax,
      total,
      status,
      created_at,
      updated_at,
      parties:party_id (
        id,
        name,
        phone
      )
    `,
    )
    .eq("id", returnId)
    .eq("user_id", currentUser.id)
    .single()

  if (returnError || !returnData) {
    return null
  }

  // Get return lines
  const { data: linesData } = await supabase
    .from("return_lines")
    .select(
      `
      id,
      return_id,
      item_id,
      quantity,
      unit_price,
      line_total,
      sales_invoice_line_id,
      purchase_invoice_line_id,
      created_at,
      inventory_items:item_id (
        id,
        name
      )
    `,
    )
    .eq("return_id", returnId)

  // Get refunds (filter by user_id)
  const { data: refundsData } = await supabase
    .from("refunds")
    .select("*")
    .eq("return_id", returnId)
    .eq("user_id", currentUser.id)
    .order("created_at", { ascending: false })

  const partyData = returnData.parties
    ? Array.isArray(returnData.parties)
      ? returnData.parties[0]
      : returnData.parties
    : null

  const totalRefunded = (refundsData ?? []).reduce((sum, r) => sum + Number(r.amount ?? 0), 0)

  return {
    id: returnData.id,
    return_number: returnData.return_number,
    type: returnData.type,
    sales_invoice_id: returnData.sales_invoice_id,
    purchase_invoice_id: returnData.purchase_invoice_id,
    party_id: returnData.party_id,
    subtotal: Number(returnData.subtotal ?? 0),
    tax: Number(returnData.tax ?? 0),
    total: Number(returnData.total ?? 0),
    status: returnData.status ?? "Draft",
    created_at: returnData.created_at,
    updated_at: returnData.updated_at,
    party: partyData
      ? {
          id: partyData.id,
          name: partyData.name,
          phone: partyData.phone,
        }
      : undefined,
    lines: (linesData ?? []).map((line: any) => {
      const itemData = line.inventory_items
        ? Array.isArray(line.inventory_items)
          ? line.inventory_items[0]
          : line.inventory_items
        : null
      return {
        id: line.id,
        return_id: line.return_id,
        item_id: line.item_id,
        quantity: Number(line.quantity ?? 0),
        unit_price: Number(line.unit_price ?? 0),
        line_total: Number(line.line_total ?? 0),
        sales_invoice_line_id: line.sales_invoice_line_id,
        purchase_invoice_line_id: line.purchase_invoice_line_id,
        created_at: line.created_at,
        item: itemData
          ? {
              id: itemData.id,
              name: itemData.name,
            }
          : undefined,
      }
    }),
    refunds: (refundsData ?? []).map((refund: any) => ({
      id: refund.id,
      return_id: refund.return_id,
      amount: Number(refund.amount ?? 0),
      method: refund.method,
      reference: refund.reference,
      created_at: refund.created_at,
    })),
    total_refunded: totalRefunded,
  }
}

export async function createRefund(payload: CreateRefundInput) {
  const currentUser = await getSessionOrRedirect()
  const supabase = createClient()

  if (!payload.return_id || payload.amount <= 0) {
    return { error: "Return ID and positive amount are required", data: null }
  }

  // Verify return exists and belongs to user
  const { data: returnData, error: returnError } = await supabase
    .from("returns")
    .select("id, total")
    .eq("id", payload.return_id)
    .eq("user_id", currentUser.id)
    .single()

  if (returnError || !returnData) {
    return { error: "Return not found", data: null }
  }

  // Get existing refunds total (filter by user_id)
  const { data: existingRefunds } = await supabase
    .from("refunds")
    .select("amount")
    .eq("return_id", payload.return_id)
    .eq("user_id", currentUser.id)

  const totalRefunded = (existingRefunds ?? []).reduce((sum, r) => sum + Number(r.amount ?? 0), 0)
  const returnTotal = Number(returnData.total ?? 0)

  if (totalRefunded + payload.amount > returnTotal) {
    return {
      error: `Refund amount exceeds return total. Maximum refundable: ${returnTotal - totalRefunded}`,
      data: null,
    }
  }

  const { data: refundData, error: refundError } = await supabase
    .from("refunds")
    .insert({
      return_id: payload.return_id,
      amount: payload.amount,
      method: payload.method,
      reference: payload.reference || null,
      user_id: currentUser.id,
    })
    .select("id")
    .single()

  if (refundError || !refundData) {
    return { error: refundError?.message ?? "Unable to create refund", data: null }
  }

  revalidatePath("/returns")
  revalidatePath("/returns/refunds")
  revalidatePath("/accounts-management")
  return { error: null, data: { refundId: refundData.id } }
}

export async function getRefunds(returnId?: string, dateFrom?: string, dateTo?: string) {
  const currentUser = await getSessionOrRedirect()
  const supabase = createClient()

  let query = supabase
    .from("refunds")
    .select(
      `
      id,
      return_id,
      amount,
      method,
      reference,
      created_at,
      returns:return_id (
        id,
        return_number,
        type,
        total,
        parties:party_id (
          id,
          name
        )
      )
    `,
    )
    .eq("user_id", currentUser.id)
    .order("created_at", { ascending: false })

  if (returnId) {
    query = query.eq("return_id", returnId)
  }

  if (dateFrom) {
    const from = dateFrom.includes("T") ? dateFrom : `${dateFrom}T00:00:00.000Z`
    query = query.gte("created_at", from)
  }

  if (dateTo) {
    const to = dateTo.includes("T") ? dateTo : `${dateTo}T23:59:59.999Z`
    query = query.lte("created_at", to)
  }

  const { data, error } = await query

  if (error) {
    return []
  }

  return (data ?? []).map((row: any) => {
    const returnData = row.returns
      ? Array.isArray(row.returns)
        ? row.returns[0]
        : row.returns
      : null
    const partyData = returnData?.parties
      ? Array.isArray(returnData.parties)
        ? returnData.parties[0]
        : returnData.parties
      : null

    return {
      id: row.id,
      return_id: row.return_id,
      amount: Number(row.amount ?? 0),
      method: row.method,
      reference: row.reference,
      created_at: row.created_at,
      return: returnData
        ? {
            id: returnData.id,
            return_number: returnData.return_number,
            type: returnData.type,
            total: Number(returnData.total ?? 0),
            party: partyData
              ? {
                  id: partyData.id,
                  name: partyData.name,
                }
              : undefined,
          }
        : undefined,
    } as Refund & { return?: Return }
  })
}
